version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:10-jdk
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "gradle/versions.gradle" }}-{{ checksum  ".circleci/config.yml" }}
      - run:
          name: Run Build
          command: ./gradlew build --console=plain
      - store_test_results:
          path: library/build/test-results/test
      - store_artifacts:
          path: library/build/reports
          destination: reports
      - run:
          name: Generate Coverage
          command: ./gradlew jacocoTestReport --console=plain
      - run:
          name: Upload Coverage
          command: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "gradle/versions.gradle" }}-{{ checksum  ".circleci/config.yml" }}
