version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: lib-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/versions.gradle" }}
      - run:
          name: Run Build
          command: ./gradlew detekt ktlintCheck build -Pkotlin.incremental=false
            -Dkotlin.compiler.execution.strategy="in-process" --console=plain --stacktrace
      - store_test_results:
          path: library/build/test-results/test
      - store_artifacts:
          path: library/build/reports
          destination: reports
      - run:
          name: Generate Coverage
          command: ./gradlew jacocoTestReport --console=plain
      - run:
          name: Upload Coverage
          command: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
            - ~/.gradle
          key: lib-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/versions.gradle" }}
