complexity:
  active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

performance:
  SpreadOperator:
    active: false

style:
  MagicNumber:
    active: false
  ForbiddenComment:
    active: false
