name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Set up Gradle Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.OS }}-gradle-${{ hashFiles('**/versions.gradle') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-${{ hashFiles('**/versions.gradle') }}
            ${{ runner.OS }}-gradle-

      - name: Build with Gradle
        run: ./gradlew ktlintCheck detekt build

      - name: Store reports
        uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: Reports
          path: library/build/reports

      - name: Upload coverage
        uses: codecov/codecov-action@v1.0.2
        env:
          CI: "true"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
