name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.2.0
        with:
          java-version: 1.8

      - name: Set up Gradle Cache
        uses: actions/cache@v1.0.3
        with:
          path: ~/.gradle/caches/modules-2
          key: ${{ runner.OS }}-gradle-${{ hashFiles('**/versions.gradle') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-${{ hashFiles('**/versions.gradle') }}
            ${{ runner.OS }}-gradle-

      - name: Build with Gradle
        run: ./gradlew ktlintCheck detekt build -Dorg.gradle.caching=false
          -Pkotlin.incremental=false -Pkapt.incremental.apt=false

      - name: Store reports
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: Reports
          path: library/build/reports
      - name: Store test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: Test results
          path: library/build/test-results/test

      - name: Upload coverage
        uses: codecov/codecov-action@v1.0.2
        env:
          CI: "true"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
